-- 예약 데이터
INSERT INTO BOOKING (BOOKING_ID, BOOKER, REPETITION_COUNT) VALUES (1, '남채희', 2);
INSERT INTO BOOKING (BOOKING_ID, BOOKER, REPETITION_COUNT) VALUES (2, '카카오', 1);
INSERT INTO BOOKING (BOOKING_ID, BOOKER, REPETITION_COUNT) VALUES (3, '사용자A', 3);
INSERT INTO BOOKING (BOOKING_ID, BOOKER, REPETITION_COUNT) VALUES (4, '사용자B', 1);
INSERT INTO BOOKING (BOOKING_ID, BOOKER, REPETITION_COUNT) VALUES (5, '사용자C', 1);
INSERT INTO BOOKING (BOOKING_ID, BOOKER, REPETITION_COUNT) VALUES (6, '사용자A', 1);

-- 예약 타임라인 데이터
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (1, 1, '회의실A', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 11:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (2, 1, '회의실A', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 11:30:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (3, 1, '회의실A', CONCAT(TO_CHAR(DATEADD('DAY', 7, CURRENT_DATE()),'yyyy-MM-dd'), ' 11:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (4, 1, '회의실A', CONCAT(TO_CHAR(DATEADD('DAY', 7, CURRENT_DATE()),'yyyy-MM-dd'), ' 11:30:00'));

INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (5, 2, '회의실B', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 10:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (6, 2, '회의실B', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 10:30:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (7, 2, '회의실B', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 11:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (8, 2, '회의실B', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 11:30:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (9, 2, '회의실B', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 12:00:00'));

INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (10, 3, '회의실C', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 15:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (11, 3, '회의실C', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 15:30:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (12, 3, '회의실C', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 16:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (13, 3, '회의실C', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 16:30:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (14, 3, '회의실C', CONCAT(TO_CHAR(DATEADD('DAY', 7, CURRENT_DATE()),'yyyy-MM-dd'), ' 15:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (15, 3, '회의실C', CONCAT(TO_CHAR(DATEADD('DAY', 7, CURRENT_DATE()),'yyyy-MM-dd'), ' 15:30:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (16, 3, '회의실C', CONCAT(TO_CHAR(DATEADD('DAY', 7, CURRENT_DATE()),'yyyy-MM-dd'), ' 16:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (17, 3, '회의실C', CONCAT(TO_CHAR(DATEADD('DAY', 7, CURRENT_DATE()),'yyyy-MM-dd'), ' 16:30:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (18, 3, '회의실C', CONCAT(TO_CHAR(DATEADD('DAY', 14, CURRENT_DATE()),'yyyy-MM-dd'), ' 15:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (19, 3, '회의실C', CONCAT(TO_CHAR(DATEADD('DAY', 14, CURRENT_DATE()),'yyyy-MM-dd'), ' 15:30:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (20, 3, '회의실C', CONCAT(TO_CHAR(DATEADD('DAY', 14, CURRENT_DATE()),'yyyy-MM-dd'), ' 16:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (21, 3, '회의실C', CONCAT(TO_CHAR(DATEADD('DAY', 14, CURRENT_DATE()),'yyyy-MM-dd'), ' 16:30:00'));

INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (22, 4, '회의실D', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 14:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (23, 4, '회의실D', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 14:30:00'));

INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (24, 5, '회의실E', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 11:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (25, 5, '회의실E', CONCAT(TO_CHAR(CURRENT_DATE(),'yyyy-MM-dd'), ' 11:30:00'));

INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (26, 6, '회의실A', CONCAT(TO_CHAR(DATEADD('DAY', 1, CURRENT_DATE()),'yyyy-MM-dd'), ' 11:00:00'));
INSERT INTO BOOKING_TIME (TIME_SEQ, BOOKING_ID, ROOM_TYPE, USE_DATE_TIME) VALUES (27, 6, '회의실A', CONCAT(TO_CHAR(DATEADD('DAY', 1, CURRENT_DATE()),'yyyy-MM-dd'), ' 11:30:00'));